feat(topology): add show labels in pools
mayadata-io/mayastor-control-plane pull request #855
Opened 2024-09-03 06:34 UTC by sinhaashish

```
[nix-shell:~/code/rust/mayastor-extensions]$ ./target/debug/kubectl-mayastor get pool pool-on-node-1 -n openebs --show-labels
 ID              DISKS                                                     MANAGED  NODE           STATUS  CAPACITY  ALLOCATED  AVAILABLE  COMMITTED  LABELS
 pool-on-node-1  aio:///dev/sdb?uuid=b324aa79-c8b3-4859-a6e8-1a51fbc5d944  true     node-1-237668  Online  10GiB     0 B        10GiB      0 B        topology-key=topology-value
```

2024-09-03 08:44 UTC, Abhinandan-Purkait requested changes

2024-09-03 08:44 UTC, Abhinandan-Purkait commented on control-plane/plugin/src/resources/pool.rs
> +                        .filter(|(key, _)| *key != &"openebs.io/created-by")
Use the created by key from constants

2024-09-03 09:13 UTC, sinhaashish commented on control-plane/plugin/src/resources/pool.rs
> +                        .filter(|(key, _)| *key != &"openebs.io/created-by")
done

2024-09-03 10:24 UTC, Abhinandan-Purkait approved these changes

2024-09-06 08:47 UTC, tiagolobocastro approved these changes

2024-09-06 08:47 UTC, tiagolobocastro commented on control-plane/plugin/src/resources/pool.rs
> +        let pools_display = PoolDisplayLabels::new_pools(pools.clone(), args.show_labels());
Doesn't seem to be used afterwards
```suggestion
        let pools_display = PoolDisplayLabels::new_pools(pools, args.show_labels());
```

2024-09-06 08:47 UTC, tiagolobocastro commented on control-plane/plugin/src/resources/pool.rs
> +pub struct PoolDisplayLabels {
This is not just displaying the labels.
Also in the future we might add other info.

```suggestion
/// The PoolDisplay structure is responsible for controlling the display formatting of Pool
/// objects. `#[serde(flatten)]` and `#[serde(skip)]` attributes are used to ensure that when the
/// object is serialised, only the `inner` object is represented.
#[derive(Serialize, Debug)]
pub struct PoolDisplay {
```

2024-09-06 08:47 UTC, tiagolobocastro commented on control-plane/plugin/src/resources/pool.rs
> +    pub(crate) fn get_pool_label_list(pool: &openapi::models::Pool) -> Vec<String> {
```suggestion
    pub(crate) fn pool_label_list(pool: &openapi::models::Pool) -> Vec<String> {
```

2024-09-06 08:47 UTC, tiagolobocastro commented on control-plane/plugin/src/resources/pool.rs
> +            rows.push(row[0].clone());
```suggestion
            let mut row = pool.row();
            if self.show_labels {
                let labelstring = PoolDisplayLabels::get_pool_label_list(pool).join(", ");
                // Add the pool labels to each row.
                row.add_cell(Cell::new(&labelstring));
            }
            rows.push(row);
```

2024-09-06 08:47 UTC, tiagolobocastro commented on control-plane/plugin/src/resources/pool.rs
> +    /// Show the labels of the pool
```suggestion
/// Arguments used when getting a pool.
#[derive(Debug, Clone, clap::Args)]
pub struct GetPoolArgs {
    /// Id of the pool.
    pool_id: PoolId,
    /// Show the labels of the pool.
```

2024-09-06 08:47 UTC, tiagolobocastro commented on control-plane/plugin/src/resources/pool.rs
> +    /// Show the labels of the pool
```suggestion
    /// Show the labels of the pool.
```

2024-09-06 12:26 UTC, sinhaashish commented
bors merge

2024-09-06 12:32 UTC, sinhaashish commented
bors merge

2024-09-06 12:35 UTC, sinhaashish commented
bors merge

2024-09-06 13:05 UTC, sinhaashish commented
bors cancel

2024-09-06 13:08 UTC, sinhaashish commented
bors merge

2024-09-06 13:33 UTC, merged